### ISSUE TITLE
bug: No cursor after glitzer is done showing progress

### ISSUE THREAD

**Issue by just-maiyak** [miampf/glitzer#21]
# Bug Report

**glitzer version:** 1.1.1 latest release

**Current behavior:** Currently `glitzer` hides the cursor and does not show it again when it's done.

**Expected behavior:** `glitzer` should show the cursor again when it's done.

**Steps to reproduce:** I encountered this bug when using glitzer in my own project gleamoire (not public yet), but I could also reproduce it by running the example on my system :

```sh
cd glitzer/example
gleam run
```

**Other information:** I am using [`kitty`](https://sw.kovidgoyal.net/kitty/) as my terminal emulator and `bash` as my shell.

**Comment by miampf** [comment]
Closed in #22
